version: '3.8'
services:
  netdata:
    image: netdata/netdata
    #hostname: example.com # set to fqdn of host
    ports:
      - target: 19999
        published: 19999
        protocol: tcp
        mode: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    deploy:
      mode: global
volumes:
  netdatalib:
  netdatacache:
