- hosts: dockers
  roles:
    - role: ericsysmin.docker.docker
      become: yes
      become-method: sudo
      ansible_become_password: "{{ sudo_vault_passwd }}"
      tags:
      - build
    - role: docker_swarm
      become: yes
      become-method: sudo
      ansible_become_password: "{{ sudo_vault_passwd }}"
      any_errors_fatal: true
      tags:
      - run